name: ut-check
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'
jobs:
  run:
    name: go test
    env:
      accessKey: ${{ secrets.ACCESSKEY }}
      secretKey: ${{ secrets.SECRETKEY }}
      QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
      QINIU_TEST_BUCKET_PRIVATE: ${{ secrets.QINIU_TEST_BUCKET_PRIVATE }}
      QINIU_TEST_RETRY: 3
      QINIU_TEST_PUNISHTIME_S: 10
      QINIU_TEST_TIMEOUT_MS: 1000
      QINIU_TEST_UP_HOSTS: ${{ secrets.QINIU_TEST_UP_HOSTS }}
      QINIU_TEST_IO_HOSTS: ${{ secrets.QINIU_TEST_IO_HOSTS }}
      QINIU_TEST_UC_HOST: ${{ secrets.QINIU_TEST_UC_HOST }}
      QINIU_TEST_RS_HOSTS: ${{ secrets.QINIU_TEST_RS_HOSTS }}
      QINIU_TEST_RSF_HOSTS: ${{ secrets.QINIU_TEST_RSF_HOSTS }}
    strategy:
      matrix:
        go-version: [1.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      # This step checks out a copy of your repository.
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go test
        env:
          GOVERSION: ${{ matrix.go-version }}
        run: |
          go test -race -coverprofile=coverage.txt `go list ./... | grep -Ev "api.v8|rpc.v7"`
          bash <(curl -s https://codecov.io/bash)
